#!/bin/sh
#
# agent     Startup script for the perl socket server
#
# chkconfig: - 89 16
# description: Lightning fast webserver with light system requirements
#
# processname: agent
. /etc/rc.d/init.d/functions

prog="/root/bin/perl_agent"
PERL="/usr/bin/perl"

RETVAL=0

start() {
        echo -n $"Starting $prog/sbin/agent"
	$PERL $prog/sbin/agent
        RETVAL=$?
        echo
        return $RETVAL
}

stop() {
        echo -n $"Stopping $prog/sbin/agent"
        kill -9 `cat $prog/logs/agent.pid`
        RETVAL=$?
        echo
        return $RETVAL
}

#status() {
#	pid=$(ps axu  | grep perl_agent | grep -v grep  | awk '{print $2}')	
#	[ -n $pid ] && RETVAL=1 || RETVAL=0
#}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                start
                ;;
	status)
		status perl
		;;
        *)
                echo $"Usage: $0 {start|stop|restart|condrestart|status}"
                RETVAL=1
esac
