#!/bin/sh

ip=$(ip address list | grep 'inet 10\.'| awk 'BEGIN {ORS=" "} {s[$NR] = $2 } END {for(x in s ) print s[x]}')
type=$(dmidecode | grep -A 8 'System Information' | grep 'Product Name:'  | awk  -F ':' '{print $2}')
serial=$(dmidecode | grep -A 8 'System Information' | grep 'Serial Number:'  | awk  -F ':' '{print $2}')
cpu_num=$(cat /proc/cpuinfo  | grep 'processor' | wc -l)
cpu_model=$(cat /proc/cpuinfo  | grep 'model name' | awk  -F ':' '{print $2}' | uniq | awk 'BEGIN{ORS=" "} END{for(x=1;x<=NF;x++) print $x}')
cpu="${cpu_num} X ${cpu_model}"
memory=$(cat /proc/meminfo | grep 'MemTotal:' | awk '{print $2/1024"MB"}')
disk=$(fdisk -l  | grep 'Disk /dev' | grep -v '/dev/mapper' | awk 'BEGIN {ORS=" "} {s[$NR] = $3 } END {for(x in s ) print s[x]"GB"}')
hostname=$(hostname)

post="ip=$ip&hostname=$hostname&type=$type&serial=$serial&cpu=$cpu&memory=$memory&disk=$disk"

md5=$(echo $post| md5sum | awk '{print $1}')

if [ -f "/tmp/cmdb" ]
then
	old_md5=$(cat /tmp/cmdb)
	if [ "$old_md5" != "$md5" ]
	then
		echo "$md5" > "/tmp/cmdb"
		curl -d "$post" -H "host:update.19lou.com" 10.1.1.107/cmdb/update
	fi
else
	echo "$md5" > "/tmp/cmdb"
	curl -d "$post" -H "host:update.19lou.com" 10.1.1.107/cmdb/update
fi
